import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("../", import.meta.url);
const names = ["bootstrap", "runner"];
const content = "// Generated by scripts/embed-python.mjs; edit runtime/python/*.py instead.\n"
	+ names.map((name) => `export const ${name.toUpperCase()}_SOURCE: string = ${JSON.stringify(readFileSync(new URL(`src/runtime/python/${name}.py`, root), "utf8").replace(/\r\n/g, "\n"))};\n`).join("");
const output = new URL("src/runtime/python-source.ts", root);
if (process.argv.includes("--check")) {
	if (readFileSync(output, "utf8").replace(/\r\n/g, "\n") !== content) {
		throw new Error("Embedded Python is stale; run npm run generate");
	}
} else {
	writeFileSync(fileURLToPath(output), content);
}
